eureka:
  client:
    # 因为当前项目为服务，不需要向服务注册自己，默认为 true
    register-with-eureka: false
    # 因为当前为非集群版 eureka，所以不需要同步其他节点数据
    fetch-registry: false
    # 当 server.port 配置不是 8761 时需要配置内容
    service-url:
      defalutZone: http://localhost:${server.port}/eureka/
server:
  port: 8761